# Generated by Django 4.2.4 on 2023-08-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_rename_name_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('Name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['Name'], 'verbose_name_plural': 'Items'},
        ),
    ]
